### ISSUE TITLE
Tom rad före while.

### ISSUE THREAD

**Issue by JohanG2012** [JSudden/Projekt#2]
Gör koden enklare att läsa.
Låg prioritet. Påverkar inte betyg.

https://github.com/JSudden/Projekt/blob/94d799614dae9e508450c2fff247f79462cfc3b2/index.php#L8

**Comment by JSudden** [comment]
Glömde fråga, ska du stänga issues efter jag har uppdaterat och du har kollat igenom vad som skulle ändras, eller ska jag göra det? Eftersom att jag anser att problemet är fixat, vet inte riktigt vad som är standard inom detta område. :bowtie:

**Comment by JohanG2012** [comment]
Du ska stänga dom :smile:
